### ISSUE TITLE
Unable to run ord index

### ISSUE THREAD

**Issue by david-dacruz** [casey/ord#1756]
Hi I'm unable to run the command `./ord --cookie-file='/Volumes/BTC-drive/core/.cookie' index`

I'm using ord 0.50 and the os is ventura

Any ideas on what I need to do to resolve this error?

Thanks ahead.

```
thread 'main' panicked at 'internal error: entered unreachable code', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/btree_iters.rs:125:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/page_manager.rs:1420:43
stack backtrace:
   0:        0x104d1a61c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb33e6e8152f78c95
   1:        0x104d3759c - core::fmt::write::hd33da007f7a27e39
   2:        0x104d144f8 - std::io::Write::write_fmt::h7edc10723862001e
   3:        0x104d1a430 - std::sys_common::backtrace::print::h895ee35b3f17b334
   4:        0x104d1bba4 - std::panicking::default_hook::{{closure}}::h3b7ee083edc2ea3e
   5:        0x104d1b8fc - std::panicking::default_hook::h4e7c2c28eba716f5
   6:        0x104d1c1c8 - std::panicking::rust_panic_with_hook::h1672176227032c45
   7:        0x104d1bfe8 - std::panicking::begin_panic_handler::{{closure}}::h0b2d072f9624d32e
   8:        0x104d1aa84 - std::sys_common::backtrace::__rust_end_short_backtrace::he9abda779115b93c
   9:        0x104d1bd44 - _rust_begin_unwind
  10:        0x104d6402c - core::panicking::panic_fmt::h23ae44661fec0889
  11:        0x104d6434c - core::result::unwrap_failed::h414a6cbb12b1e143
  12:        0x104b9e568 - <redb::tree_store::page_store::page_manager::TransactionalMemory as core::ops::drop::Drop>::drop::hf98d563b42fc9843
  13:        0x104b8065c - core::ptr::drop_in_place<redb::tree_store::page_store::page_manager::TransactionalMemory>::h39dfdd614afec84b
  14:        0x104b819c4 - redb::db::Database::new::hda61c185f31cfb31
  15:        0x104711860 - redb::db::Builder::open_mmapped::h752375f327702d56
  16:        0x104994c04 - ord::index::Index::open::h16b0d912a6cbbee8
  17:        0x104772a40 - ord::subcommand::index::run::had3f01aa398edc02
  18:        0x10494bbfc - ord::subcommand::Subcommand::run::h46f011610a7b7443
  19:        0x104857b58 - ord::main::hc77e65098a7cd891
  20:        0x1046e1d90 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2264e4a00b60689a
  21:        0x1046e1da8 - std::rt::lang_start::{{closure}}::hde67c2e1ddfc7fd8
  22:        0x104d0e818 - std::rt::lang_start_internal::h00a235e820a7f01c
  23:        0x1046e1d78 - _main
thread panicked while panicking. aborting.
[1]    22261 abort      ./ord --cookie-file='/Volumes/BTC-drive/core/.cookie' index```

**Comment by greywoods33** [comment]
Delete the index file and restart indexing.

**Comment by david-dacruz** [comment]
Thanks @greywoods33 mate what index file exactly?
